title: Ronald Seoh
description: I'm currently a graduate student in the <a href="https://www.cics.umass.edu/">College of Information and Computer Sciences</a> at the University of Massachusetts Amherst. I'm broadly interested in artificial intelligence and machine learning, with the current focus on Bayesian inference and Bayesian deep learning. <br>In my previous life, I worked as an analyst for the Equity Derivatives Division of <a href="https://eng.bond.co.kr">KIS Pricing Inc.</a>, an affliate (subsidiary) of <a href="https://www.moodys.com/researchandratings/">Moody's Investor Service</a>. I received a MSc in Management Science from London School of Economics, where my disseration advisor was <a href="http://personal.lse.ac.uk/veghl/">László A. Végh</a>. I received a BA in Computer Science and Business from <a href="https://www.brandeis.edu/">Brandeis University</a>.
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
